---
title: "5000HW2-Data Gathering and Cleaning"
author: "Lan Cao"
date: "2023-09-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install packages and get datasets

```{r}
install.packages("educationdata")
library(educationdata)


virtual_school_2015 <- get_education_data(level = "schools",
                         source = "ccd",
                         topic = "directory",
                         filters = list(year = 2015,
                                        virtual = 1)
                                          )


virtual_school_2020 <- get_education_data(level = "schools",
                         source = "ccd",
                         topic = "directory",
                         filters = list(year = 2020,
                                        virtual = 1)
                                          )

write.csv(virtual_school_2015, file = "virtual_school_2015.csv")
write.csv(virtual_school_2020, file = "virtual_school_2020.csv")

```

## Initial Data Cleaning

```{r}
library(tidyverse)

sub_15 <- virtual_school_2015 %>% 
    select(year, school_name, state_location, school_level, school_type, charter, magnet, virtual, enrollment) %>% 
    filter(!is.na(enrollment)) %>%
    mutate(virtual = replace(virtual, TRUE , "Yes"))
 
sub_15 <- sub_15 %>% 
    mutate(school_level = ifelse(school_level == 1, "Primary", school_level),
           school_level = ifelse(school_level == 2, "Middle", school_level),
           school_level = ifelse(school_level == 3, "High", school_level),
           school_level = ifelse(school_level == 4, "Other", school_level))

sub_15 <- sub_15 %>%
    mutate(school_type = ifelse(school_type == 1, "Regular", school_type),
           school_type = ifelse(school_type == 2, "Special", school_type),
           school_type = ifelse(school_type == 3, "Vocational", school_type),
           school_type = ifelse(school_type == 4, "Other", school_type))

sub_15 <- sub_15 %>%
   mutate(charter = ifelse(charter == 0, "No", charter),
          charter = ifelse(charter == 1, "Yes", charter),
          charter = ifelse(charter == -2, "Not applicable", charter))
  
sub_15 <- sub_15 %>%
   mutate(charter = ifelse(charter == 0, "No", charter),
          charter = ifelse(charter == 1, "Yes", charter),
          charter = ifelse(charter == -2, "Not applicable", charter))  
  

sub_15 <- sub_15 %>%
   mutate(magnet = ifelse(magnet == 0, "No", magnet),
          magnet = ifelse(magnet == 1, "Yes", magnet),
          magnet = ifelse(magnet == -1, "Missing/not reported", magnet),
          magnet = ifelse(magnet == -2, "Not applicable", magnet)) 

sub_15 <- sub_15 %>% 
    mutate(enrollment = ifelse(enrollment == -1, "Missing/not reported", enrollment)) %>%
    select(year, state_location,school_name, school_level, school_type, enrollment, charter, magnet,virtual)

write.csv(sub_15, "cleaned_virtual_school_2015.csv")



```


